image: node:12

stages:
  - installation
  - lint

frontend-installation:
  stage: installation
  artifacts:
    paths:
      - frontend/node_modules
  script:
    - cd frontend
    - npm install

frontend-lint:
  stage: lint
  needs: ["frontend-installation"]
  script:
    - cd frontend
    - ./node_modules/.bin/eslint ./

backend-installation:
  stage: installation
  artifacts:
    paths:
      - backend/node_modules
  script:
    - cd backend
    - npm install

backend-lint:
  stage: lint
  needs: ["backend-installation"]
  allow_failure: true
  script:
    - cd backend
    - ./node_modules/.bin/eslint ./
